apiVersion: v1
kind: Service
metadata:
  name: vote
  labels:
    app: vote
spec:
  type: NodePort
  ports:
    - name: "vote-service"
      targetPort: 80
      port: 80
      nodePort: 31000
  selector:
    app: vote
